### ISSUE TITLE
Replace JSDOM dependency

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-index-files#352]
Looking the distribution size of this action, I noticed that it has a size of 11 MB unpacked (2.5 MB packed) out of which 30% are taken by JSDOM, alone.

Based on this article:

https://webreflection.medium.com/linkedom-a-jsdom-alternative-53dd8f699311

I looked at `linkedom` as alternative, and our tests as well as sample pages on our current projects run through without any problems.

**Comment by trieloff** [comment]
If all you need is `querySelectorAll` and `textContent`, then https://github.com/syntax-tree/hast-util-select might suffice.

**Comment by dominique-pfister** [comment]
Cool, even smaller, and much more advanced, will definitely take a look 🙏

**Comment by trieloff** [comment]
You'll have to use the Unified AST API instead of DOM, though and not all selectors are supported.

**Comment by dominique-pfister** [comment]
The list of selectors supported looks fine!

I went along and replaced the current `JSDOM(html).window)` with:
```
  const { parse } = require('parse5');
  const fromParse5 = require('hast-util-from-parse5');
  const { selectAll } = require('hast-util-select');
  ...
  const hast = fromParse5(parse(html));
  ...
  const elements = selectAll(selector, hast);
```

and noticed that the elements returned are not `HTMLElement`s and therefore no longer support:
- `el.textContent`: could be achieved with `hast-util-to-string `
- `el.getAttribute`: could be achieved by wading through an element's `properties`
- `el.innerHTML`: no replacement found, though no project currently uses `innerHTML`

Furthermore, the latest versions of those libraries are ESMs and no longer support CJS.

**Comment by trieloff** [comment]
The ESM migration is going to hit us for most active dependencies sooner or later.
