### ISSUE TITLE
Failing to load index configuration should not silently continue

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-index-files#57]
In lines:

https://github.com/adobe/helix-index-files/blob/845bda3d611f1bf5b74c27819093a035ed337075/src/index.js#L49-L61

a missing index file gets silently replaced with a static definition. Shouldn't we rather report such a problem, @trieloff , as well as a badly formatted YAML file?

**Comment by trieloff** [comment]
The `sha`, `path`, `type`, `parents`, and `branch` properties are useful for structural search no matter what. But I agree, that a proper error log would be useful, too.
