### ISSUE TITLE
Add "creation date" to index entries

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-index-files#69]
Index entries are composed of page extracted data. For better sorting, it would be useful to add the create date to each index entry.
For theblog, the only date we have and we sort on is like '02/11/2020'. When blog entries are the same day: order between those entires is determine by the response from Algolia and cannot be controlled.

**Comment by tripodsan** [comment]
I merged the PR, however, I think the creation date is also quite arbitrary. 
eventually, they probably want to use a score or similar to figure our the most relevant post of the day.
or sort them lexically.

**Comment by kptdobe** [comment]
This would be useful during the import to keep the existing order. 
Yes, for newly created posts, they will need a different system.
