### ISSUE TITLE
Monitor Setup is failling in CI

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-index-files#9]
**Description**
https://circleci.com/gh/adobe/helix-index-files/25

@rofe, can you check?

**Comment by rofe** [comment]
We need https://github.com/adobe/helix-continuous/issues/50 for this.

**Comment by rofe** [comment]
If it's not a web action, I suggest we disable monitoring for now.

**Comment by rofe** [comment]
I recommend upgrading helix-status dependency to v5+. See also https://github.com/adobe/helix-continuous/tree/master/.circleci/orbs/helix-post-deploy

**Comment by rofe** [comment]
If this is not a web action by design, therefore our current monitoring can't be used.
